services:
  kwil-postgres:
    image: "kwildb/postgres:16.8-1"
    hostname: kwil-postgres
    shm_size: 2G
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    # persis data
    volumes:
      - ${POSTGRES_VOLUME:-data-kwil-postgres}:/var/lib/postgresql/data
    networks:
      - tn-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
        tag: "{{.Name}}"

  tn-db:
    container_name: tn-db
    hostname: tn-db
    image: "tn-db:local"
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./deployments/Dockerfile
      # For local development, if cache is not supported, please comment the following lines
      cache_from:
        - ${CACHE_FROM:-type=local,src=/tmp/buildx-cache}/tn-db
      cache_to:
        - ${CACHE_TO:-type=local,dest=/tmp/buildx-cache-new}/tn-db
      args:
        - CHAIN_ID=${CHAIN_ID:-trufnetwork-dev}
    environment:
      CONFIG_PATH: /root/.kwild
      # app.pg-db-host
      KWILD_DB_HOST: kwil-postgres
      # DB_OWNER must be provided at runtime
      DB_OWNER: ${DB_OWNER:-}
    ports:
      - "50051:50051"
      - "50151:50151"
      - "${TN_RPC_PORT:-8484}:8484"
      - "8080:8080"
      - "26656:26656"
    depends_on:
      kwil-postgres:
        condition: service_healthy
    volumes:
      - ${TN_VOLUME:-data-tn-db}:/root/.kwild
    networks:
      - tn-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
        tag: "{{.Name}}"

networks:
  tn-network:
    driver: bridge
    name: tn-network

volumes:
  data-kwil-postgres:
  data-tn-db: